services:
  database:
    image: postgres:16-alpine
    container_name: roadsafety-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
      PGTZ: ${POSTGRES_PGTZ:-Europe/Moscow}
    ports:
      - "127.0.0.1:${POSTGRES_EXTERNAL_PORT:-5432}:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roadsafety-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 30 
    ports:
      - "${PGADMIN_EXTERNAL_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy
    networks:
      - roadsafety-net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  roadsafety-net:
    driver: bridge